/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        psi: {
          // All theme-dependent — see the :root / :root.dark blocks in
          // src/index.css. These are just the plumbing so bg-psi-x /
          // text-psi-x classes repaint automatically on theme toggle.
          bg: 'var(--psi-bg)',
          bgAlt: 'var(--psi-bg-alt)',
          surface: 'var(--psi-surface)',
          surface2: 'var(--psi-surface-2)',
          surface3: 'var(--psi-surface-3)',
          border: 'var(--psi-border)',
          borderSoft: 'var(--psi-border-soft)',
          borderStrong: 'var(--psi-border-strong)',
          borderBtn: 'var(--psi-border-btn)',
          borderDashed: 'var(--psi-border-dashed)',
          hairline: 'var(--psi-hairline)',
          orange: 'var(--psi-orange)',
          orangeLite: 'var(--psi-orange-lite)',
          orangeDeep: 'var(--psi-orange-deep)',
          ok: 'var(--psi-ok)',
          ink: 'var(--psi-ink)',
          text: 'var(--psi-text)',
          text2: 'var(--psi-text-2)',
          muted: 'var(--psi-muted)',
          muted2: 'var(--psi-muted-2)',
          muted3: 'var(--psi-muted-3)',
          muted4: 'var(--psi-muted-4)',
          muted5: 'var(--psi-muted-5)',
          dim: 'var(--psi-dim)',
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        'psi-xl': '22px',
        'psi-lg': '20px',
        'psi-md': '18px',
        'psi-sm': '16px',
        'psi-btn': '14px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'psi-cta': '0 18px 40px rgba(255,163,26,.32)',
        'psi-cta-sm': '0 8px 22px rgba(255,163,26,.30)',
        'psi-play': '0 20px 55px rgba(255,163,26,.45)',
        'psi-window': '0 40px 100px rgba(var(--psi-shadow-rgb),.10), 0 0 0 1px rgba(255,163,26,.16)',
        'psi-card-3d': '0 30px 70px rgba(var(--psi-shadow-rgb),.14)',
        'psi-frame': '0 35px 90px rgba(var(--psi-shadow-rgb),.16)',
        'psi-step': '0 20px 50px rgba(var(--psi-shadow-rgb),.10)',
        'psi-featured': '0 30px 70px rgba(var(--psi-shadow-rgb),.12)',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'psi-h1': ['clamp(42px,7vw,86px)', { lineHeight: '0.97', letterSpacing: '-0.035em' }],
        'psi-h2': ['clamp(32px,4.4vw,52px)', { lineHeight: '1.04', letterSpacing: '-0.03em' }],
        'psi-h2-lg': ['clamp(34px,5vw,60px)', { lineHeight: '1.03', letterSpacing: '-0.03em' }],
        'psi-h2-sm': ['clamp(30px,4.2vw,48px)', { lineHeight: '1.06', letterSpacing: '-0.03em' }],
        'psi-lead': ['clamp(16px,1.7vw,19px)', { lineHeight: '1.65' }],
        'psi-eyebrow': ['11.5px', { letterSpacing: '0.16em' }],
        'psi-micro': ['10.5px', { letterSpacing: '0.13em' }],
        'psi-pill': ['10px', { letterSpacing: '0.09em' }],
      },
      transitionTimingFunction: {
        psi: 'cubic-bezier(.2,.8,.2,1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        'psi-float': {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-14px)' },
        },
        'psi-drift': {
          '0%,100%': { transform: 'translate3d(0,0,0) scale(1)' },
          '50%': { transform: 'translate3d(3%,-4%,0) scale(1.08)' },
        },
        'psi-marquee': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        'psi-pulse': {
          '0%,100%': { boxShadow: '0 0 0 0 rgba(255,163,26,.45)' },
          '70%': { boxShadow: '0 0 0 18px rgba(255,163,26,0)' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        'psi-float': 'psi-float 9s ease-in-out infinite',
        'psi-float-slow': 'psi-float 11s ease-in-out infinite 1s',
        'psi-drift': 'psi-drift 16s ease-in-out infinite',
        'psi-drift-slow': 'psi-drift 22s ease-in-out infinite reverse',
        'psi-marquee': 'psi-marquee 34s linear infinite',
        'psi-pulse': 'psi-pulse 2.4s infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}